[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 500

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#D98328"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#00234E"
font = "sans serif"
