"""SQL-backed persistent storage (PostgreSQL or SQLite)."""

from __future__ import annotations

import json
import os
from datetime import datetime
from pathlib import Path
from typing import Any

import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine

STORE_DIR = Path(__file__).resolve().parents[1] / "data" / "store"
DEFAULT_SQLITE_URL = f"sqlite:///{STORE_DIR / 'recyclage.db'}"


def _database_url() -> str:
    url = os.environ.get("DATABASE_URL", DEFAULT_SQLITE_URL).strip()
    if url.startswith("postgres://"):
        url = url.replace("postgres://", "postgresql://", 1)
    return url


def get_engine() -> Engine:
    STORE_DIR.mkdir(parents=True, exist_ok=True)
    engine = create_engine(_database_url(), pool_pre_ping=True)
    return engine


def backend_label() -> str:
    url = _database_url()
    if url.startswith("postgresql"):
        return "PostgreSQL"
    return "SQLite"


def init_schema(engine: Engine | None = None) -> None:
    engine = engine or get_engine()
    ddl = """
    CREATE TABLE IF NOT EXISTS client_db (
        tel TEXT PRIMARY KEY,
        data TEXT NOT NULL,
        updated_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS history_rows (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tel TEXT NOT NULL,
        row_hash TEXT NOT NULL UNIQUE,
        data TEXT NOT NULL,
        created_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS onoff_calls (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tel TEXT NOT NULL,
        duration_seconds INTEGER NOT NULL DEFAULT 0,
        call_date TEXT,
        call_time TEXT,
        direction TEXT,
        row_hash TEXT NOT NULL UNIQUE,
        created_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS onoff_totals (
        tel TEXT PRIMARY KEY,
        total_duration_seconds INTEGER NOT NULL DEFAULT 0,
        total_duration TEXT,
        call_count INTEGER NOT NULL DEFAULT 0,
        updated_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS app_meta (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS vente_baseline (
        tel TEXT PRIMARY KEY,
        statut TEXT NOT NULL,
        couleur TEXT,
        updated_at TEXT NOT NULL
    );
    CREATE TABLE IF NOT EXISTS vente_results (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        tel TEXT NOT NULL,
        jour_vente TEXT NOT NULL,
        statut_origine TEXT,
        couleur_origine TEXT,
        source_baseline TEXT,
        matched INTEGER NOT NULL DEFAULT 0,
        nom TEXT,
        prenom TEXT,
        analyzed_at TEXT NOT NULL,
        batch_id TEXT NOT NULL
    );
    CREATE INDEX IF NOT EXISTS idx_history_tel ON history_rows (tel);
    CREATE INDEX IF NOT EXISTS idx_onoff_tel ON onoff_calls (tel);
    CREATE INDEX IF NOT EXISTS idx_onoff_totals_tel ON onoff_totals (tel);
    CREATE INDEX IF NOT EXISTS idx_vente_results_batch ON vente_results (batch_id);
    CREATE INDEX IF NOT EXISTS idx_vente_results_jour ON vente_results (jour_vente);
    """
    if engine.dialect.name == "postgresql":
        ddl = ddl.replace("AUTOINCREMENT", "GENERATED BY DEFAULT AS IDENTITY")

    with engine.begin() as conn:
        for statement in ddl.strip().split(";"):
            stmt = statement.strip()
            if stmt:
                conn.execute(text(stmt))


def _row_hash(parts: list[str]) -> str:
    return "|".join(str(p) for p in parts)


def _df_row_to_json(row: pd.Series) -> str:
    payload = row.to_dict()
    cleaned = {}
    for key, value in payload.items():
        if pd.isna(value):
            cleaned[key] = None
        elif isinstance(value, (pd.Timestamp, datetime)):
            cleaned[key] = value.isoformat()
        else:
            cleaned[key] = value
    return json.dumps(cleaned, default=str)


def _json_rows_to_df(rows: list[dict[str, str]]) -> pd.DataFrame:
    if not rows:
        return pd.DataFrame()
    records = [json.loads(row["data"]) for row in rows]
    return pd.DataFrame(records)


def store_has_data(engine: Engine | None = None) -> bool:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        client_count = conn.execute(text("SELECT COUNT(*) FROM client_db")).scalar_one()
        hist_count = conn.execute(text("SELECT COUNT(*) FROM history_rows")).scalar_one()
    return client_count > 0 and hist_count > 0


def load_meta(engine: Engine | None = None) -> dict[str, Any]:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        row = conn.execute(text("SELECT value FROM app_meta WHERE key = 'meta'")).fetchone()
    if not row:
        return {"updates": []}
    return json.loads(row[0])


def save_meta(meta: dict[str, Any], engine: Engine | None = None) -> None:
    engine = engine or get_engine()
    init_schema(engine)
    payload = json.dumps(meta, default=str)
    dialect = engine.dialect.name
    with engine.begin() as conn:
        if dialect == "postgresql":
            conn.execute(
                text(
                    """
                    INSERT INTO app_meta (key, value) VALUES ('meta', :value)
                    ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
                    """
                ),
                {"value": payload},
            )
        else:
            conn.execute(text("DELETE FROM app_meta WHERE key = 'meta'"))
            conn.execute(
                text("INSERT INTO app_meta (key, value) VALUES ('meta', :value)"),
                {"value": payload},
            )


def _dedupe_client_rows(df: pd.DataFrame) -> pd.DataFrame:
    """One row per canonical TEL (last wins). Handles int/str duplicates."""
    if df.empty or "TEL" not in df.columns:
        return df
    out = df.copy()
    out["TEL"] = out["TEL"].astype(str).str.strip()
    out = out[out["TEL"].notna() & (out["TEL"] != "") & (out["TEL"].str.lower() != "nan")]
    return out.drop_duplicates(subset=["TEL"], keep="last").reset_index(drop=True)


def _client_db_insert_sql(dialect: str, *, replace_all: bool) -> str:
    if dialect == "postgresql":
        if replace_all:
            return (
                "INSERT INTO client_db (tel, data, updated_at) "
                "VALUES (:tel, :data, :updated_at)"
            )
        return (
            """
            INSERT INTO client_db (tel, data, updated_at)
            VALUES (:tel, :data, :updated_at)
            ON CONFLICT (tel) DO UPDATE SET
                data = EXCLUDED.data,
                updated_at = EXCLUDED.updated_at
            """
        )
    if replace_all:
        return (
            "INSERT OR REPLACE INTO client_db (tel, data, updated_at) "
            "VALUES (:tel, :data, :updated_at)"
        )
    return (
        "INSERT OR REPLACE INTO client_db (tel, data, updated_at) "
        "VALUES (:tel, :data, :updated_at)"
    )


def replace_client_db(df: pd.DataFrame, engine: Engine | None = None) -> None:
    engine = engine or get_engine()
    init_schema(engine)
    now = datetime.now().isoformat(timespec="seconds")
    if df.empty:
        with engine.begin() as conn:
            conn.execute(text("DELETE FROM client_db"))
        return
    df = _dedupe_client_rows(df)
    by_tel: dict[str, dict[str, str]] = {}
    for _, row in df.iterrows():
        tel = str(row["TEL"]).strip()
        by_tel[tel] = {"tel": tel, "data": _df_row_to_json(row), "updated_at": now}
    rows = list(by_tel.values())
    dialect = engine.dialect.name
    with engine.begin() as conn:
        conn.execute(text("DELETE FROM client_db"))
        if rows:
            conn.execute(text(_client_db_insert_sql(dialect, replace_all=True)), rows)


def upsert_client_db(df: pd.DataFrame, engine: Engine | None = None) -> int:
    """Insert or update client rows keyed by TEL."""
    engine = engine or get_engine()
    init_schema(engine)
    if df.empty:
        return 0
    df = _dedupe_client_rows(df)
    now = datetime.now().isoformat(timespec="seconds")
    by_tel: dict[str, dict[str, str]] = {}
    for _, row in df.iterrows():
        tel = str(row["TEL"]).strip()
        by_tel[tel] = {"tel": tel, "data": _df_row_to_json(row), "updated_at": now}
    rows = list(by_tel.values())
    dialect = engine.dialect.name
    with engine.begin() as conn:
        if rows:
            conn.execute(text(_client_db_insert_sql(dialect, replace_all=False)), rows)
    return len(rows)


def load_client_db(engine: Engine | None = None) -> pd.DataFrame:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        result = conn.execute(text("SELECT data FROM client_db"))
        records = [json.loads(row[0]) for row in result.fetchall()]
    return pd.DataFrame(records)


def replace_history(df: pd.DataFrame, engine: Engine | None = None) -> None:
    engine = engine or get_engine()
    init_schema(engine)
    now = datetime.now().isoformat(timespec="seconds")
    with engine.begin() as conn:
        conn.execute(text("DELETE FROM history_rows"))
        if df.empty:
            return
        _insert_history_rows(conn, df, now)


def append_history(df: pd.DataFrame, engine: Engine | None = None) -> int:
    engine = engine or get_engine()
    init_schema(engine)
    if df.empty:
        return 0
    before = count_history_rows(engine)
    now = datetime.now().isoformat(timespec="seconds")
    with engine.begin() as conn:
        _insert_history_rows(conn, df, now)
    return count_history_rows(engine) - before


def _insert_history_rows(conn, df: pd.DataFrame, now: str) -> None:
    dedupe_cols = ["TEL"]
    for col in ("DATE", "HEURE", "STATUS", "DATETIME"):
        if col in df.columns:
            dedupe_cols.append(col)

    rows = []
    seen: set[str] = set()
    for _, row in df.iterrows():
        hash_parts = [row.get(col, "") for col in dedupe_cols]
        row_hash = _row_hash(hash_parts)
        if row_hash in seen:
            continue
        seen.add(row_hash)
        rows.append(
            {
                "tel": str(row["TEL"]),
                "row_hash": row_hash,
                "data": _df_row_to_json(row),
                "created_at": now,
            }
        )

    if not rows:
        return

    dialect = conn.dialect.name
    if dialect == "postgresql":
        conn.execute(
            text(
                """
                INSERT INTO history_rows (tel, row_hash, data, created_at)
                VALUES (:tel, :row_hash, :data, :created_at)
                ON CONFLICT (row_hash) DO NOTHING
                """
            ),
            rows,
        )
    else:
        conn.execute(
            text(
                """
                INSERT OR IGNORE INTO history_rows (tel, row_hash, data, created_at)
                VALUES (:tel, :row_hash, :data, :created_at)
                """
            ),
            rows,
        )


def load_history(engine: Engine | None = None) -> pd.DataFrame:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        result = conn.execute(text("SELECT data FROM history_rows"))
        records = [json.loads(row[0]) for row in result.fetchall()]
    return pd.DataFrame(records)


def count_history_rows(engine: Engine | None = None) -> int:
    engine = engine or get_engine()
    with engine.begin() as conn:
        return int(conn.execute(text("SELECT COUNT(*) FROM history_rows")).scalar_one())


def replace_onoff_calls(df: pd.DataFrame, engine: Engine | None = None) -> None:
    engine = engine or get_engine()
    init_schema(engine)
    now = datetime.now().isoformat(timespec="seconds")
    with engine.begin() as conn:
        conn.execute(text("DELETE FROM onoff_calls"))
        if df.empty:
            return
        _insert_onoff_rows(conn, df, now)


def append_onoff_calls(df: pd.DataFrame, engine: Engine | None = None) -> int:
    engine = engine or get_engine()
    init_schema(engine)
    if df.empty:
        return 0
    before = count_onoff_rows(engine)
    now = datetime.now().isoformat(timespec="seconds")
    with engine.begin() as conn:
        _insert_onoff_rows(conn, df, now)
    return count_onoff_rows(engine) - before


def _insert_onoff_rows(conn, df: pd.DataFrame, now: str) -> None:
    rows = []
    seen: set[str] = set()
    for _, row in df.iterrows():
        call_date = str(row.get("CALL_DATE", "") or "")
        call_time = str(row.get("CALL_TIME", "") or "")
        direction = str(row.get("DIRECTION", "") or "")
        duration = int(row.get("Duration_Seconds", 0) or 0)
        tel = str(row["TEL"])
        row_hash = _row_hash([tel, duration, call_date, call_time, direction])
        if row_hash in seen:
            continue
        seen.add(row_hash)
        rows.append(
            {
                "tel": tel,
                "duration_seconds": duration,
                "call_date": call_date or None,
                "call_time": call_time or None,
                "direction": direction or None,
                "row_hash": row_hash,
                "created_at": now,
            }
        )

    if not rows:
        return

    dialect = conn.dialect.name
    sql = (
        """
        INSERT INTO onoff_calls
        (tel, duration_seconds, call_date, call_time, direction, row_hash, created_at)
        VALUES (:tel, :duration_seconds, :call_date, :call_time, :direction, :row_hash, :created_at)
        """
        + (" ON CONFLICT (row_hash) DO NOTHING" if dialect == "postgresql" else "")
    )
    if dialect != "postgresql":
        sql = sql.replace("INSERT INTO", "INSERT OR IGNORE INTO")
    conn.execute(text(sql), rows)


def load_onoff_calls(engine: Engine | None = None) -> pd.DataFrame:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        result = conn.execute(
            text(
                """
                SELECT tel, duration_seconds, call_date, call_time, direction
                FROM onoff_calls
                """
            )
        )
        rows = result.fetchall()
    if not rows:
        return pd.DataFrame(columns=["TEL", "Duration_Seconds"])
    from engine.processor import _clean_tel_db

    df = pd.DataFrame(
        [
            {
                "TEL": row[0],
                "Duration_Seconds": row[1],
                "CALL_DATE": row[2],
                "CALL_TIME": row[3],
                "DIRECTION": row[4],
            }
            for row in rows
        ]
    )
    df["TEL"] = _clean_tel_db(df["TEL"])
    return df


def replace_onoff_totals(df: pd.DataFrame, engine: Engine | None = None) -> None:
    """Replace per-TEL Onoff duration totals (from merged exports / totals sheets)."""
    from engine.processor import _clean_tel_db, _format_duration

    engine = engine or get_engine()
    init_schema(engine)
    now = datetime.now().isoformat(timespec="seconds")
    with engine.begin() as conn:
        conn.execute(text("DELETE FROM onoff_totals"))
        if df.empty:
            return

        out = df.copy()
        if "TEL" not in out.columns:
            return
        out["TEL"] = _clean_tel_db(out["TEL"])
        if "Total_Duration_Seconds" not in out.columns:
            return
        out["Total_Duration_Seconds"] = (
            pd.to_numeric(out["Total_Duration_Seconds"], errors="coerce").fillna(0).astype(int)
        )
        if "Total_Duration" not in out.columns:
            out["Total_Duration"] = out["Total_Duration_Seconds"].map(_format_duration)
        if "Call_Count" not in out.columns:
            out["Call_Count"] = 0
        out = out.drop_duplicates(subset=["TEL"], keep="last")

        rows = [
            {
                "tel": str(row["TEL"]),
                "total_duration_seconds": int(row["Total_Duration_Seconds"]),
                "total_duration": str(row["Total_Duration"]),
                "call_count": int(row.get("Call_Count", 0) or 0),
                "updated_at": now,
            }
            for _, row in out.iterrows()
        ]
        if rows:
            dialect = engine.dialect.name
            if dialect == "postgresql":
                sql = """
                    INSERT INTO onoff_totals
                    (tel, total_duration_seconds, total_duration, call_count, updated_at)
                    VALUES (:tel, :total_duration_seconds, :total_duration, :call_count, :updated_at)
                    ON CONFLICT (tel) DO UPDATE SET
                        total_duration_seconds = EXCLUDED.total_duration_seconds,
                        total_duration = EXCLUDED.total_duration,
                        call_count = EXCLUDED.call_count,
                        updated_at = EXCLUDED.updated_at
                """
            else:
                sql = """
                    INSERT OR REPLACE INTO onoff_totals
                    (tel, total_duration_seconds, total_duration, call_count, updated_at)
                    VALUES (:tel, :total_duration_seconds, :total_duration, :call_count, :updated_at)
                """
            conn.execute(text(sql), rows)


def load_onoff_totals(engine: Engine | None = None) -> pd.DataFrame:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        result = conn.execute(
            text(
                """
                SELECT tel, total_duration_seconds, total_duration, call_count
                FROM onoff_totals
                """
            )
        )
        rows = result.fetchall()
    if not rows:
        return pd.DataFrame(columns=["TEL", "Total_Duration_Seconds", "Total_Duration", "Call_Count"])
    from engine.processor import _clean_tel_db

    return pd.DataFrame(
        [
            {
                "TEL": row[0],
                "Total_Duration_Seconds": row[1],
                "Total_Duration": row[2],
                "Call_Count": row[3],
            }
            for row in rows
        ]
    ).assign(TEL=lambda d: _clean_tel_db(d["TEL"]))


def count_onoff_totals(engine: Engine | None = None) -> int:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        return int(conn.execute(text("SELECT COUNT(*) FROM onoff_totals")).scalar_one())


def count_onoff_rows(engine: Engine | None = None) -> int:
    engine = engine or get_engine()
    with engine.begin() as conn:
        return int(conn.execute(text("SELECT COUNT(*) FROM onoff_calls")).scalar_one())


def count_client_rows(engine: Engine | None = None) -> int:
    engine = engine or get_engine()
    with engine.begin() as conn:
        return int(conn.execute(text("SELECT COUNT(*) FROM client_db")).scalar_one())


def count_client_tels(engine: Engine | None = None) -> int:
    return count_client_rows(engine)


def migrate_pickle_store_if_needed(engine: Engine | None = None) -> bool:
    """One-time migration from legacy .pkl files to SQL storage."""
    engine = engine or get_engine()
    if store_has_data(engine):
        return False

    db_pkl = STORE_DIR / "client_db.pkl"
    hist_pkl = STORE_DIR / "history.pkl"
    onoff_pkl = STORE_DIR / "onoff_calls.pkl"
    if not db_pkl.exists() or not hist_pkl.exists():
        return False

    replace_client_db(pd.read_pickle(db_pkl), engine)
    replace_history(pd.read_pickle(hist_pkl), engine)
    if onoff_pkl.exists():
        replace_onoff_calls(pd.read_pickle(onoff_pkl), engine)

    meta_path = STORE_DIR / "meta.json"
    if meta_path.exists():
        save_meta(json.loads(meta_path.read_text(encoding="utf-8")), engine)
    return True


def replace_vente_baseline(df: pd.DataFrame, engine: Engine | None = None) -> int:
    """Replace the active vente baseline snapshot (TEL → statut avant ventes)."""
    engine = engine or get_engine()
    init_schema(engine)
    now = datetime.now().isoformat(timespec="seconds")
    with engine.begin() as conn:
        conn.execute(text("DELETE FROM vente_baseline"))
        if df.empty:
            return 0
        rows = []
        for _, row in df.iterrows():
            rows.append(
                {
                    "tel": str(row["TEL"]),
                    "statut": str(row.get("Statut", row.get("statut", ""))),
                    "couleur": str(row.get("Couleur", row.get("couleur", "")) or ""),
                    "updated_at": now,
                }
            )
        conn.execute(
            text(
                "INSERT INTO vente_baseline (tel, statut, couleur, updated_at) "
                "VALUES (:tel, :statut, :couleur, :updated_at)"
            ),
            rows,
        )
    return len(df)


def load_vente_baseline(engine: Engine | None = None) -> pd.DataFrame:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        result = conn.execute(
            text("SELECT tel, statut, couleur, updated_at FROM vente_baseline")
        )
        rows = result.mappings().all()
    if not rows:
        return pd.DataFrame(columns=["TEL", "Statut", "Couleur", "updated_at"])
    df = pd.DataFrame(rows)
    return df.rename(
        columns={"tel": "TEL", "statut": "Statut", "couleur": "Couleur"}
    )


def count_vente_baseline(engine: Engine | None = None) -> int:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        return int(conn.execute(text("SELECT COUNT(*) FROM vente_baseline")).scalar_one())


def append_vente_results(
    df: pd.DataFrame,
    *,
    batch_id: str,
    analyzed_at: str | None = None,
    engine: Engine | None = None,
) -> int:
    """Persist analyzed vente rows for daily history."""
    engine = engine or get_engine()
    init_schema(engine)
    if df.empty:
        return 0
    ts = analyzed_at or datetime.now().isoformat(timespec="seconds")
    rows = []
    for _, row in df.iterrows():
        rows.append(
            {
                "tel": str(row.get("TEL", "")),
                "jour_vente": str(row.get("Jour_Vente", "")),
                "statut_origine": str(row.get("Statut_origine", "")),
                "couleur_origine": str(row.get("Couleur_origine", "")),
                "source_baseline": str(row.get("Source_baseline", "")),
                "matched": 1 if bool(row.get("Matched", False)) else 0,
                "nom": str(row.get("NOM", "") or ""),
                "prenom": str(row.get("PRENOM", "") or ""),
                "analyzed_at": ts,
                "batch_id": batch_id,
            }
        )
    with engine.begin() as conn:
        conn.execute(
            text("DELETE FROM vente_results WHERE batch_id = :batch_id"),
            {"batch_id": batch_id},
        )
        conn.execute(
            text(
                """
                INSERT INTO vente_results (
                    tel, jour_vente, statut_origine, couleur_origine, source_baseline,
                    matched, nom, prenom, analyzed_at, batch_id
                ) VALUES (
                    :tel, :jour_vente, :statut_origine, :couleur_origine, :source_baseline,
                    :matched, :nom, :prenom, :analyzed_at, :batch_id
                )
                """
            ),
            rows,
        )
    return len(rows)


def load_vente_results(engine: Engine | None = None) -> pd.DataFrame:
    engine = engine or get_engine()
    init_schema(engine)
    with engine.begin() as conn:
        result = conn.execute(
            text(
                """
                SELECT tel, jour_vente, statut_origine, couleur_origine, source_baseline,
                       matched, nom, prenom, analyzed_at, batch_id
                FROM vente_results
                ORDER BY analyzed_at DESC, jour_vente DESC
                """
            )
        )
        rows = result.mappings().all()
    if not rows:
        return pd.DataFrame()
    df = pd.DataFrame(rows)
    return df.rename(
        columns={
            "tel": "TEL",
            "jour_vente": "Jour_Vente",
            "statut_origine": "Statut_origine",
            "couleur_origine": "Couleur_origine",
            "source_baseline": "Source_baseline",
            "matched": "Matched",
            "nom": "NOM",
            "prenom": "PRENOM",
            "analyzed_at": "Analyzed_at",
            "batch_id": "Batch_id",
        }
    )
